services:
  db:
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-botler}
  bot:
    image: shimbot:dev
    build:
      dockerfile: ./docker/Dockerfile.dev
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-botler}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
